# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '基本UI控件的使用' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 基本UI控件的使用
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
end
